### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ariG23498** [ayulockin/grid-solver-with-obstacle#2]
* How do we represent the states in this problem.
* The states need to be later compared.
* The state generator method needs to be standardized too.
* The bot needs to be pointing to the same `position` irrespective of the position that it is in.

We will be using our model on the positive coordinate system
<img src="https://cdn.kastatic.org/ka-perseus-graphie/f4f55e21651d6077308082714a90f1fb19e98447.svg">
The coordinates are `(x,y)`

**Comment by ayulockin** [comment]
This looks good.
